# Insert chapter 2 title here

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.

```{r}
date()
```

Here we go again...

#*opening relevant libraries*
library(tidyverse)
library(readr)
library(dplyr)
library(ggplot2)
#*reading the csv data set, looking at its structure and dimensions. It has 7 variables and 166 rows, one of the variables is a string variable with characters stored in it (gender) and 6 other variables are floats (double precision floats)*
lrn_csv <- read_csv("lrn_analysis.csv",col_names = TRUE)
str(lrn_csv)
dim(lrn_csv)

#*I Chose the variables for analysis: gender, age, attitude, and surf. The idea is to test how the emotions-related variables are associated with points students received at statistics exam, controlling for gender and age. Firstly, we explore the variables by summarising them, first, the variable points by gender with minimum max, average and standard deviation and then age, attitude, surf*
lrn_csv %>% 
  group_by(gender) %>% 
    summarise(min(points), max(points), mean(points), sd(points))
#*tibble shows that women performed slightly worse in exam, but the difference is marginal*    

lrn_csv %>% 
  summarise(min(age), max(age), mean(age), sd(age))
#*This helps to get to know who are the study participants. Students vary in age from 17 to 55 years, with an average at 25.5, and standard deviation of 7.77*
lrn_csv %>% 
  summarise(min(attitude), max(attitude), mean(attitude), sd(attitude))
#*the attitude is an index for attitude towards statistics, a subjective measurement that takes a minimum value at 14 and maximum at 50, with a mean of 31.4 and standard deviation of 7.3*
lrn_csv %>% 
  summarise(min(surf), max(surf), mean(surf), sd(surf))
#*surf is a composite variable based on likert scale variables (1-5 points) for opinion measurement from strongly disagree to strongly agree. The mean value is 2.8 with a standard deviation of 0.5. The questions concern subjective opinion related to interest in statistics course, feeling of whether the course is actually worth going to. I hypothesise that this variable reflects on inner motivation of student to complete the course, that may directly influence the final exam score. Given the formulation of sub-questions such as "There's not much of the work here that I find interesting or relevant", in general students are closer to agreeing with low interest in the course.*

#*Next is graphics. Getting the scatter plots of exam points against our independent variables to have a first glimpse of the association.*

lrn_csv %>% 
  ggplot(aes(x = attitude, y = points)) +
  geom_point()
#*this scatter plot displays dots for attitude and exam score. From the picture, it is clear that the more positive the attitude is, the higher would be the points.*

lrn_csv %>% 
  ggplot(aes(x = surf, y = points)) +
  geom_point()
#*The association of surf and points variables does not give as clear of a result as in previous scatter. Although, a trend of a backwards relation can be observed, meaning that the higher the value of surf variable, the lower would be the points, that is supporting the hypothesis*

lrn_csv %>% 
  ggplot(aes(x = age, y = points)) +
  geom_point()
#*Looking at age and points plot, we can see that most of the students are between 18 and 25 years of age, and there is an upward trend of raising age and points toghether, yet not linear. If the sample was bigger, we could have tried dividing it to age groups, as there are different trends for those under 25s and those older than that, but here it is inappropriate*

#*regression. Fitting a linear regression models, introducing variables stepwise for points as dependent and our variables of interest: attitude and surf as independent, and then controlling also for gender and age.*
help(lm)

model1 <- lm(points ~ attitude, data = lrn_csv)
summary(model1)
  
model2 <- lm(points ~ attitude + surf, data = lrn_csv)
summary(model2)

model3 <- lm(points ~ attitude + surf + gender + age, data = lrn_csv)
summary(model3)

#*Looking at the outputs of three models, it is clear that attitude variable has the most explanatory power as the firt model ezxplains 19.8% of the variance in the outcome variable, and the introduction of the othe three variables increases the value of r squared only marginally. Attitude is the only variable associated with the exam points, so that the more positive the attitude towards statistics in general, the higher would be the exam scores, partly supporting the hypothesis. Association of surf variable with an outcome is not statistically significant, that goes against the hypothesis.*  
#*Discussion.*
#*Need to know more about the attitude variable to be able to speculate on the possible reasons for such association.*