---
title: "chapter5.Rmd"
author: "nuriiar"
date: "`r Sys.Date()`"
output: html_document
---

#PCA and MCA

```{r libr}
#unpacking the libraries
library(dplyr)
library(corrplot)
library(GGally)
library(tidyverse)
set.seed(1)
#reading the data
human <- read.csv("human.csv", header = T, row.names = 1)

colnames(human)
str(human)
#exploring the relations
ggpairs(human)

cor(human) %>% corrplot()
```



```{r PCA}
#PCA
pca_human <- prcomp(human)
summary(pca_human)
biplot(pca_human, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```
```{r PCA_std}
#PCA for standardised data
human_std <- scale(human)
pca_human_std <- prcomp(human_std)
summary(pca_human_std)
biplot(pca_human_std, choices = 1:2, cex = c(0.8, 1), col = c("grey40", "deeppink2"))

```
Tea data
```{r MCA}
#install.packages("FactoMineR")
library(ggplot2)
library(FactoMineR)
tea <- read.csv("https://raw.githubusercontent.com/KimmoVehkalahti/Helsinki-Open-Data-Science/master/datasets/tea.csv", stringsAsFactors = TRUE)

keep_columns <- c("Tea", "How", "how", "sugar", "where", "lunch")
tea_time <- select(tea, keep_columns)

#pivot_longer(tea_time, cols = everything()) %>% ggplot(aes(value)) + facet_wrap("name", scales = "free")
mca <- MCA(tea_time, graph = FALSE)
plot(mca, invisible=c("ind"),habillage = "quali")
```
MCA